#!/bin/sh

### BEGIN INIT INFO
# Provides:          spaceapi 
# Required-Start:    networking 
# Required-Stop:     networking
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: starts the spaceapiclient 
# Description:       starts the spaceapiclient
### END INIT INFO

case "$1" in
  start)
    echo "Starting SpaceApiClient "
        # init
	cd /opt/SpaceApiClient/
        nohup ./spaceapiclient.php >> /var/log/spaceapi.log 2>&1 &
    ;;
  stop)
    echo "Stopping SpaceApiClient "
	/opt/SpaceApiClient/stop.php
	killall spaceapiclient.php
    ;;
  restart)
    echo "Restarting SpaceApiClient"
    /etc/init.d/spaceapi stop
    sleep 1
    /etc/init.d/spaceapi start
    ;;
  status)
      iptables -L
      ;;
  *)
    N=/etc/init.d/$NAME
    echo "Usage: $N {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
